"""Trace luồng hoạt động của chatbot với follow-up questions."""

import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

print("="*80)
print("TRACE LUỒNG HOẠT ĐỘNG - Follow-up Questions")
print("="*80)
print()

# Scenario mô phỏng
print("SCENARIO:")
print("Turn 1: User hỏi 'Sodium là gì?'")
print("Turn 2: User hỏi 'Cấu hình electron của nó?'")
print()
print("="*80)
print()

# TURN 1
print("TURN 1: 'Sodium là gì?'")
print("-" * 80)

print("\n[Node 1] rephrase_query")
print("  Input: 'Sodium là gì?'")
print("  Context: (không có - lần đầu)")
print("  Output: rephrased_query = 'Sodium là gì?'")

print("\n[Node 2] check_relevance")
print("  Input: rephrased_query = 'Sodium là gì?'")
print("  Output: is_chemistry_related = true")

print("\n[Node 3] extract_and_validate")
print("  Input: rephrased_query = 'Sodium là gì?'")
print("  Prompt: 'Mở rộng query với keywords CHUẨN IUPAC'")
print("  LLM xử lý:")
print("    - Nhận dạng: 'Sodium' là tên nguyên tố")
print("    - Chuẩn hóa: 'Sodium' → 'Sodium Na'")
print("    - Mở rộng: Thêm ký hiệu nguyên tố")
print("  Output: search_query = 'Sodium Na element'")
print("          is_valid = true")

print("\n[Node 4] retrieve_from_rag")
print("  Input: search_query = 'Sodium Na element'")
print("  Hybrid search:")
print("    - Dense vector: semantic search 'Sodium Na element'")
print("    - Sparse BM25: exact match 'Na'")
print("  Output: rag_context = [")
print("    {")
print("      'iupac_name': 'Sodium',")
print("      'formula': 'Na',")
print("      'type': 'element',")
print("      'doc_id': 'sodium',")
print("      'score': 1.0")
print("    }")
print("  ]")

print("\n[Node 5] generate_response")
print("  Input:")
print("    - rephrased_query = 'Sodium là gì?'  ← QUAN TRỌNG: Câu hỏi gốc")
print("    - rag_context = [Sodium Na]")
print("  LLM xử lý:")
print("    - Nhận dạng compound: Sodium (Na)")
print("    - Câu hỏi: 'là gì?' → Tổng quan")
print("    - Tạo thông tin cơ bản về Sodium")
print("  Output:")
print("    - text_response: 'Sodium (Na) là nguyên tố...'")
print("    - selected_doc_id: 'sodium'")
print("    - should_return_image: true")
print("    - should_return_audio: true")

print("\n" + "="*80)
print()

# TURN 2
print("TURN 2: 'Cấu hình electron của nó?' (Follow-up)")
print("-" * 80)

print("\n[Node 1] rephrase_query")
print("  Input: 'Cấu hình electron của nó?'")
print("  Context: Previous Q&A về Sodium")
print("    - Last question: 'Sodium là gì?'")
print("    - Last answer: 'Sodium (Na) là nguyên tố...'")
print("  LLM xử lý:")
print("    - Phát hiện đại từ: 'nó'")
print("    - Thay thế từ context: 'nó' → 'Sodium'")
print("  Output: rephrased_query = 'Cấu hình electron của Sodium?'")
print("                                    ✓ ĐÃ CHUYỂN ĐỔI THÀNH STANDALONE")

print("\n[Node 2] check_relevance")
print("  Input: rephrased_query = 'Cấu hình electron của Sodium?'")
print("  Output: is_chemistry_related = true")

print("\n[Node 3] extract_and_validate ← ĐIỂM QUAN TRỌNG")
print("  Input: rephrased_query = 'Cấu hình electron của Sodium?'")
print("  Prompt: 'Mở rộng query với keywords CHUẨN IUPAC'")
print("  LLM xử lý:")
print("    - Nhận dạng compound: 'Sodium'")
print("    - Chuẩn hóa: 'Sodium' → 'Sodium Na'")
print("    - NOTE: Context 'cấu hình electron' KHÔNG được thêm vào search_query")
print("    - WHY? Vì extract_and_validate CHỈ lo IDENTIFICATION, không lo về question type")
print("  Output: search_query = 'Sodium Na element'")
print("          is_valid = true")
print()
print("  ⚠️  LƯU Ý: 'cấu hình electron' KHÔNG có trong search_query!")
print("  ✓  NHƯNG ĐÂY LÀ OK! Vì:")
print("     - search_query chỉ dùng để TÌM compound")
print("     - rephrased_query vẫn giữ nguyên 'Cấu hình electron của Sodium?'")
print("     - generate_response sẽ dùng rephrased_query để biết user hỏi gì")

print("\n[Node 4] retrieve_from_rag")
print("  Input: search_query = 'Sodium Na element'")
print("  Output: rag_context = [")
print("    {")
print("      'iupac_name': 'Sodium',")
print("      'formula': 'Na',")
print("      'type': 'element',")
print("      'doc_id': 'sodium',")
print("      'score': 1.0")
print("    }")
print("  ]")
print("  ✓ Tìm đúng compound (Sodium)")

print("\n[Node 5] generate_response ← ĐIỂM QUYẾT ĐỊNH")
print("  Input:")
print("    - rephrased_query = 'Cấu hình electron của Sodium?'  ← CONTEXT VẪN CÒN!")
print("    - rag_context = [Sodium Na]")
print()
print("  LLM prompt:")
print("    '''")
print("    Câu hỏi: Cấu hình electron của Sodium?")
print("    Kết quả tìm kiếm:")
print("    - Tên: Sodium")
print("    - Công thức: Na")
print("    - Loại: element")
print("    '''")
print()
print("  LLM xử lý:")
print("    - Nhận dạng compound: Sodium (Na)")
print("    - Câu hỏi cụ thể: 'Cấu hình electron'")
print("    - Dùng LLM knowledge để trả lời:")
print("      * Sodium có Z = 11")
print("      * Cấu hình electron: 1s² 2s² 2p⁶ 3s¹")
print("      * Hoặc [Ne] 3s¹")
print()
print("  Output:")
print("    - text_response: 'Cấu hình electron của Sodium (Na):")
print("                      1s² 2s² 2p⁶ 3s¹ hoặc [Ne] 3s¹...'")
print("    - selected_doc_id: 'sodium'")
print("    - should_return_image: false  (câu hỏi cụ thể, không cần hình)")
print("    - should_return_audio: false")

print("\n" + "="*80)
print()

# KẾT LUẬN
print("KẾT LUẬN:")
print("="*80)
print()
print("✓ FLOW HOẠT ĐỘNG ĐÚNG với follow-up questions!")
print()
print("Lý do:")
print("1. rephrase_query chuyển 'nó' → 'Sodium' ✓")
print("2. extract_and_validate CHỈ dùng để:")
print("   - Chuẩn hóa tên compound theo IUPAC")
print("   - Tạo search_query để TÌM compound")
print("   - KHÔNG cần giữ context về question type")
print()
print("3. generate_response nhận:")
print("   - rephrased_query = 'Cấu hình electron của Sodium?' ← CONTEXT ĐẦY ĐỦ")
print("   - rag_context = [Sodium] ← COMPOUND ĐÚNG")
print("   → Có thể trả lời chính xác!")
print()
print("4. Phân chia nhiệm vụ rõ ràng:")
print("   - extract_and_validate: IDENTIFICATION (tìm compound gì?)")
print("   - generate_response: QUESTION ANSWERING (hỏi gì về compound đó?)")
print()
print("="*80)
print()

# TEST CASE KHÁC
print("TEST CASE KHÁC:")
print("-" * 80)
print()
print("Scenario: User hỏi 'Ethanol là gì?' → 'Công thức phân tử của nó?'")
print()
print("Turn 2 flow:")
print("1. rephrase: 'nó' → 'Ethanol'")
print("   Output: 'Công thức phân tử của Ethanol?'")
print()
print("2. extract_and_validate:")
print("   Input: 'Công thức phân tử của Ethanol?'")
print("   Output: search_query = 'Ethanol C2H6O'")
print()
print("3. retrieve: Tìm Ethanol")
print()
print("4. generate:")
print("   - Câu hỏi: 'Công thức phân tử của Ethanol?'")
print("   - Compound: Ethanol")
print("   - Answer: 'Công thức phân tử của Ethanol là C₂H₆O hoặc C₂H₅OH...'")
print()
print("✓ HOẠT ĐỘNG CHÍNH XÁC!")
print()
print("="*80)
